# This is a basic workflow that is manually triggered
# good for testing
# actions appear from default branch - https://github.community/t/workflow-files-only-picked-up-from-master/16129/2

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      service:
        description: 'Service to deploy (folder to use)'
        default: 'example-app'
        required: true
      environment:
        description: 'The environment'
        default: 'development'
        required: true
      branch:
        description: 'Branch To Use'
        default: 'develop'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: node:lts

    strategy:
      matrix:
        node: [ '12' ]
    name: Using Node ${{ matrix.node }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/checkout@v2
        with:
          # set the checkout branch
          ref: ${{ github.event.inputs.branch }}
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      #     check-latest: true

      - name: Make shell script executable
        run: chmod +x ./${{ github.event.inputs.service }}/deploy-gcr.sh
      # Runs a single command using the runners shell
      - name: Send greeting
        run: |
          gcloud info
          echo "CI is $CI"
          export CI="true"
          echo "Service: ${{ github.event.inputs.service }}"
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "CI: $CI"
          cd ${{ github.event.inputs.service }}
          ./deploy-gcr.sh ${{ github.event.inputs.environment }}
