# This is a basic workflow that is manually triggered
# good for testing
# actions appear from default branch - https://github.community/t/workflow-files-only-picked-up-from-master/16129/2

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      service:
        description: 'Service to deploy (folder to use)'
        default: 'example-app'
        required: true
      environment:
        description: 'The environment'
        default: 'development'
        required: true
      # TOREMOVE
      # branch:
      #   description: 'Branch To Use'
      #   default: 'develop'
      #   required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: node:lts

    strategy:
      matrix:
        node: [ '14' ]

    name: Deploying ${{ github.event.inputs.service }} - ${{ github.event.inputs.environment }}... Using Node ${{ matrix.node }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/checkout@v2
        # TOREMOVE
        # with:
        #   ref: ${{ github.event.inputs.branch }}
      - name: Show checkout branch name
        # UNVERIFIED also can try $(echo $GITHUB_REF | cut -d'/' -f 3)
        run: echo checking out on branch ${GITHUB_REF##*/}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Make shell script executable
        run: |
          chmod +x ./${{ github.event.inputs.service }}/update.sh
          chmod +x ./${{ github.event.inputs.service }}/deploy.sh
      # Runs a single command using the runners shell
      - name: Initiate Deployment
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          # VAULT_<env> to VAULT
          VAULT: ${{ secrets[format('VAULT_{0}', github.event.inputs.environment)] }}
        run: |
          # gcloud info
          echo "CI: $CI"
          echo "Service: ${{ github.event.inputs.service }}"
          echo "Branch: ${GITHUB_REF##*/}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          cd ${{ github.event.inputs.service }}
          ./update.sh
          ./deploy.sh ${{ github.event.inputs.environment }}
